name: Build Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    name: "offline tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"
          cache: true
      - uses: actions/checkout@v4
        if: ${{ vars.INF_TOOLS_GO_REPOSITORY != '' }}
        with:
          repository: ${{ vars.INF_TOOLS_GO_REPOSITORY }}
          path: consumer
      - run: make check
        env:
          INF_TOOLS_GO_ROOT: ${{ vars.INF_TOOLS_GO_REPOSITORY != '' && format('{0}/consumer', github.workspace) || '' }}
      - run: make build
  push:
    name: "inf-backup"
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/dhw-pcs/inf-backup:latest
            ghcr.io/dhw-pcs/inf-backup:3
            ghcr.io/dhw-pcs/inf-backup:3.0.1
            ghcr.io/dhw-pcs/inf-backup:${{ github.sha }}
